(define (problem uav_problem_u3_r0_l20_p25_c101_g10_ct2)
(:domain uav_domain)
(:objects
	uav1 - helicopter
	uav2 - helicopter
	uav3 - helicopter
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	crate52 - crate
	crate53 - crate
	crate54 - crate
	crate55 - crate
	crate56 - crate
	crate57 - crate
	crate58 - crate
	crate59 - crate
	crate60 - crate
	crate61 - crate
	crate62 - crate
	crate63 - crate
	crate64 - crate
	crate65 - crate
	crate66 - crate
	crate67 - crate
	crate68 - crate
	crate69 - crate
	crate70 - crate
	crate71 - crate
	crate72 - crate
	crate73 - crate
	crate74 - crate
	crate75 - crate
	crate76 - crate
	crate77 - crate
	crate78 - crate
	crate79 - crate
	crate80 - crate
	crate81 - crate
	crate82 - crate
	crate83 - crate
	crate84 - crate
	crate85 - crate
	crate86 - crate
	crate87 - crate
	crate88 - crate
	crate89 - crate
	crate90 - crate
	crate91 - crate
	crate92 - crate
	crate93 - crate
	crate94 - crate
	crate95 - crate
	crate96 - crate
	crate97 - crate
	crate98 - crate
	crate99 - crate
	crate100 - crate
	crate101 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
)
(:init
	(obj_at uav1 depot)
	(heli_free uav1)
	(obj_at uav2 depot)
	(heli_free uav2)
	(obj_at uav3 depot)
	(heli_free uav3)
	(obj_at crate1 depot)
	(crate_content crate1 food)
	(obj_at crate2 depot)
	(crate_content crate2 food)
	(obj_at crate3 depot)
	(crate_content crate3 food)
	(obj_at crate4 depot)
	(crate_content crate4 food)
	(obj_at crate5 depot)
	(crate_content crate5 food)
	(obj_at crate6 depot)
	(crate_content crate6 food)
	(obj_at crate7 depot)
	(crate_content crate7 food)
	(obj_at crate8 depot)
	(crate_content crate8 food)
	(obj_at crate9 depot)
	(crate_content crate9 food)
	(obj_at crate10 depot)
	(crate_content crate10 food)
	(obj_at crate11 depot)
	(crate_content crate11 food)
	(obj_at crate12 depot)
	(crate_content crate12 food)
	(obj_at crate13 depot)
	(crate_content crate13 food)
	(obj_at crate14 depot)
	(crate_content crate14 food)
	(obj_at crate15 depot)
	(crate_content crate15 food)
	(obj_at crate16 depot)
	(crate_content crate16 food)
	(obj_at crate17 depot)
	(crate_content crate17 food)
	(obj_at crate18 depot)
	(crate_content crate18 food)
	(obj_at crate19 depot)
	(crate_content crate19 food)
	(obj_at crate20 depot)
	(crate_content crate20 food)
	(obj_at crate21 depot)
	(crate_content crate21 food)
	(obj_at crate22 depot)
	(crate_content crate22 food)
	(obj_at crate23 depot)
	(crate_content crate23 food)
	(obj_at crate24 depot)
	(crate_content crate24 food)
	(obj_at crate25 depot)
	(crate_content crate25 food)
	(obj_at crate26 depot)
	(crate_content crate26 food)
	(obj_at crate27 depot)
	(crate_content crate27 food)
	(obj_at crate28 depot)
	(crate_content crate28 food)
	(obj_at crate29 depot)
	(crate_content crate29 food)
	(obj_at crate30 depot)
	(crate_content crate30 food)
	(obj_at crate31 depot)
	(crate_content crate31 food)
	(obj_at crate32 depot)
	(crate_content crate32 food)
	(obj_at crate33 depot)
	(crate_content crate33 food)
	(obj_at crate34 depot)
	(crate_content crate34 food)
	(obj_at crate35 depot)
	(crate_content crate35 food)
	(obj_at crate36 depot)
	(crate_content crate36 food)
	(obj_at crate37 depot)
	(crate_content crate37 food)
	(obj_at crate38 depot)
	(crate_content crate38 food)
	(obj_at crate39 depot)
	(crate_content crate39 food)
	(obj_at crate40 depot)
	(crate_content crate40 food)
	(obj_at crate41 depot)
	(crate_content crate41 food)
	(obj_at crate42 depot)
	(crate_content crate42 food)
	(obj_at crate43 depot)
	(crate_content crate43 food)
	(obj_at crate44 depot)
	(crate_content crate44 food)
	(obj_at crate45 depot)
	(crate_content crate45 food)
	(obj_at crate46 depot)
	(crate_content crate46 food)
	(obj_at crate47 depot)
	(crate_content crate47 food)
	(obj_at crate48 depot)
	(crate_content crate48 food)
	(obj_at crate49 depot)
	(crate_content crate49 food)
	(obj_at crate50 depot)
	(crate_content crate50 food)
	(obj_at crate51 depot)
	(crate_content crate51 food)
	(obj_at crate52 depot)
	(crate_content crate52 food)
	(obj_at crate53 depot)
	(crate_content crate53 food)
	(obj_at crate54 depot)
	(crate_content crate54 food)
	(obj_at crate55 depot)
	(crate_content crate55 food)
	(obj_at crate56 depot)
	(crate_content crate56 food)
	(obj_at crate57 depot)
	(crate_content crate57 food)
	(obj_at crate58 depot)
	(crate_content crate58 food)
	(obj_at crate59 depot)
	(crate_content crate59 food)
	(obj_at crate60 depot)
	(crate_content crate60 food)
	(obj_at crate61 depot)
	(crate_content crate61 food)
	(obj_at crate62 depot)
	(crate_content crate62 food)
	(obj_at crate63 depot)
	(crate_content crate63 food)
	(obj_at crate64 depot)
	(crate_content crate64 food)
	(obj_at crate65 depot)
	(crate_content crate65 food)
	(obj_at crate66 depot)
	(crate_content crate66 food)
	(obj_at crate67 depot)
	(crate_content crate67 food)
	(obj_at crate68 depot)
	(crate_content crate68 food)
	(obj_at crate69 depot)
	(crate_content crate69 food)
	(obj_at crate70 depot)
	(crate_content crate70 food)
	(obj_at crate71 depot)
	(crate_content crate71 food)
	(obj_at crate72 depot)
	(crate_content crate72 food)
	(obj_at crate73 depot)
	(crate_content crate73 food)
	(obj_at crate74 depot)
	(crate_content crate74 food)
	(obj_at crate75 depot)
	(crate_content crate75 food)
	(obj_at crate76 depot)
	(crate_content crate76 food)
	(obj_at crate77 depot)
	(crate_content crate77 food)
	(obj_at crate78 depot)
	(crate_content crate78 food)
	(obj_at crate79 depot)
	(crate_content crate79 food)
	(obj_at crate80 depot)
	(crate_content crate80 food)
	(obj_at crate81 depot)
	(crate_content crate81 food)
	(obj_at crate82 depot)
	(crate_content crate82 food)
	(obj_at crate83 depot)
	(crate_content crate83 food)
	(obj_at crate84 depot)
	(crate_content crate84 food)
	(obj_at crate85 depot)
	(crate_content crate85 food)
	(obj_at crate86 depot)
	(crate_content crate86 food)
	(obj_at crate87 depot)
	(crate_content crate87 food)
	(obj_at crate88 depot)
	(crate_content crate88 medicine)
	(obj_at crate89 depot)
	(crate_content crate89 medicine)
	(obj_at crate90 depot)
	(crate_content crate90 medicine)
	(obj_at crate91 depot)
	(crate_content crate91 medicine)
	(obj_at crate92 depot)
	(crate_content crate92 medicine)
	(obj_at crate93 depot)
	(crate_content crate93 medicine)
	(obj_at crate94 depot)
	(crate_content crate94 medicine)
	(obj_at crate95 depot)
	(crate_content crate95 medicine)
	(obj_at crate96 depot)
	(crate_content crate96 medicine)
	(obj_at crate97 depot)
	(crate_content crate97 medicine)
	(obj_at crate98 depot)
	(crate_content crate98 medicine)
	(obj_at crate99 depot)
	(crate_content crate99 medicine)
	(obj_at crate100 depot)
	(crate_content crate100 medicine)
	(obj_at crate101 depot)
	(crate_content crate101 medicine)
	(obj_at person1 loc5)
	(obj_at person2 loc4)
	(obj_at person3 loc3)
	(obj_at person4 loc17)
	(obj_at person5 loc3)
	(obj_at person6 loc19)
	(obj_at person7 loc7)
	(obj_at person8 loc12)
	(obj_at person9 loc7)
	(obj_at person10 loc16)
	(obj_at person11 loc19)
	(obj_at person12 loc3)
	(obj_at person13 loc19)
	(obj_at person14 loc20)
	(obj_at person15 loc18)
	(obj_at person16 loc6)
	(obj_at person17 loc20)
	(obj_at person18 loc20)
	(obj_at person19 loc20)
	(obj_at person20 loc1)
	(obj_at person21 loc19)
	(obj_at person22 loc7)
	(obj_at person23 loc13)
	(obj_at person24 loc1)
	(obj_at person25 loc10)
)
(:goal (and

	(obj_at uav1 depot)
	(obj_at uav2 depot)
	(obj_at uav3 depot)

	(obj_at uav1 depot)
	(obj_at uav2 depot)
	(obj_at uav3 depot)

	(obj_at uav1 depot)
	(obj_at uav2 depot)
	(obj_at uav3 depot)
	(preson_crate person1 food )
	(preson_crate person4 medicine )
	(preson_crate person12 medicine )
	(preson_crate person14 medicine )
	(preson_crate person16 medicine )
	(preson_crate person20 medicine )
	(preson_crate person21 medicine )
	(preson_crate person22 medicine )
	(preson_crate person23 medicine )
	(preson_crate person25 food )
	))
)
